module.exports = [
  { value: '', label: 'none', image: '' },
	{ value: 'hp', label: 'HP+', image: '/images/awakenings/1.png' },
  { value: 'atk', label: 'ATK+', image: '/images/awakenings/2.png' },
  { value: 'rcv', label: 'RCV+', image: '/images/awakenings/3.png' },
  { value: 'fire-res', label: 'Fire Res', image: '/images/awakenings/4.png' },
  { value: 'water-res', label: 'Water Res', image: '/images/awakenings/5.png' },
  { value: 'wood-res', label: 'Wood Res', image: '/images/awakenings/6.png' },
  { value: 'light-res', label: 'Light Res', image: '/images/awakenings/7.png' },
  { value: 'dark-res', label: 'Dark Res', image: '/images/awakenings/8.png' },
  { value: 'heal', label: 'Heal', image: '/images/awakenings/9.png' },
  { value: 'bind-res', label: 'Bind Res', image: '/images/awakenings/10.png' },
  { value: 'blind', label: 'Blind Res', image: '/images/awakenings/11.png' },
  { value: 'jammer', label: 'Jammer Res', image: '/images/awakenings/12.png' },
  { value: 'poison', label: 'Poison Res', image: '/images/awakenings/13.png' },
  { value: 'fire-p', label: 'Fire Enhance', image: '/images/awakenings/14.png' },
  { value: 'water-p', label: 'Water Enhance', image: '/images/awakenings/15.png' },
  { value: 'wood-p', label: 'Wood Enhance', image: '/images/awakenings/16.png' },
  { value: 'light-p', label: 'Light Enhance', image: '/images/awakenings/17.png' },
  { value: 'dark-p', label: 'Dark Enhance', image: '/images/awakenings/18.png' },
  { value: 'time', label: 'Time Extend', image: '/images/awakenings/19.png' },
  { value: 'bind-rec', label: 'Bind Rec', image: '/images/awakenings/20.png' },
  { value: 'skill', label: 'Skill', image: '/images/awakenings/21.png' },
  { value: 'fire-r', label: 'Fire Row', image: '/images/awakenings/22.png' },
  { value: 'water-r', label: 'Water Row', image: '/images/awakenings/23.png' },
  { value: 'wood-r', label: 'Wood Row', image: '/images/awakenings/24.png' },
  { value: 'light-r', label: 'Light Row', image: '/images/awakenings/25.png' },
  { value: 'dark-r', label: 'Dark Row', image: '/images/awakenings/26.png' },
  { value: 'tpa', label: 'TPA', image: '/images/awakenings/27.png' },
  { value: 'skill-res', label: 'TPA', image: '/images/awakenings/28.png' },
  { value: 'heart-p', label: 'Heart Enhance', image: '/images/awakenings/29.png' },
  { value: 'multi', label: 'Multi Boost', image: '/images/awakenings/30.png' },
  { value: 'dragon-k', label: 'Dragon Killer', image: '/images/awakenings/31.png' },
  { value: 'god-k', label: 'God Killer', image: '/images/awakenings/32.png' },
  { value: 'devil-k', label: 'Devil Killer', image: '/images/awakenings/33.png' },
  { value: 'machine-k', label: 'Machine Killer', image: '/images/awakenings/34.png' },
  { value: 'attacker-k', label: 'Attacker Killer', image: '/images/awakenings/35.png' },
  { value: 'physical-k', label: 'Physical Killer', image: '/images/awakenings/36.png' },
  { value: 'healer-k', label: 'Healer Killer', image: '/images/awakenings/37.png' },
  { value: 'balanced-k', label: 'Balanced Killer', image: '/images/awakenings/38.png' },
  { value: 'awoken-k', label: 'Awoken Killer', image: '/images/awakenings/39.png' },
  { value: 'enhance-k', label: 'Enhance Killer', image: '/images/awakenings/40.png' },
  { value: 'redeem-k', label: 'Redeem Killer', image: '/images/awakenings/41.png' },
  { value: 'evo-k', label: 'Evo Killer', image: '/images/awakenings/42.png' },
  { value: '7combo', label: '7 Combo', image: '/images/awakenings/43.png' },
  { value: 'guardbreak', label: '7 Combo', image: '/images/awakenings/44.png' },
  { value: 'fua', label: 'FUA', image: '/images/awakenings/45.png' },
  { value: 'hp-team', label: 'HP Team', image: '/images/awakenings/46.png' },
  { value: 'rcv-team', label: 'RCV Team', image: '/images/awakenings/47.png' },
  { value: '9orb', label: 'Void Damage', image: '/images/awakenings/48.png' },
];
